# .github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # or your matrix of versions

      - name: Install Poetry
        uses: snok/install-poetry@v1   # installs Poetry and adds it to PATH :contentReference[oaicite:0]{index=0}

      - name: Configure Poetry venv
        run: |
          # keep venv inside project so we can cache it
          poetry config virtualenvs.in-project true

      - name: Cache Virtualenv
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}  # invalidates when lock changes :contentReference[oaicite:1]{index=1}

      - name: Install Dependencies
        run: poetry install --no-interaction --no-ansi  # installs both dependencies and your package :contentReference[oaicite:2]{index=2}

      - name: Run Tests
        run: poetry run pytest -q
